# Solvers

El paquete ``warehouse_allocation`` soporta resolver el problema de Chung  <cite data-cite="2019:chung"> Chung </cite> adicionando restricciones propias como las de pesos por clusters o divisiones.

A continuación se muestra como resolver el problema usando data sintética.

In [1]:
import pickle

# Cargamos data de ejemplo
with open("data", "rb") as ip:
    example_data = pickle.load(ip)

example_data.keys()

dict_keys(['D', 'Z', 'W', 'WT', 'OCM', 'division_types', 'Z_DIV'])

``èxample_data`` es un diccionario con parámetros reales, donde ``D`` corresponde al vector de demandas, `Z` la capacidad de los cluters, `W` el vector de pesos, `WT` es la tolerancia de los clusters seteada, `OCM` es la matriz de afinidad, `Z_DIV` corresponde la capacidad de los clusters considerando divisiones/rotaciones y `division_types` corresponde al valor de división/rotación de cada sku.

In [2]:
# Demanda de los skus
print(example_data["D"])

[   8   10    2    4    4    9  144   97    5   41  114  223   52  305
    1    5    4    4  389  139  696    2  190  257  260  194  333  349
  144    4  354  147  122   96  107  191  205  201  234   60   55  226
  397  143    9  113  120  904 1568 1011  157 1027 1360  995    1  134
   15    9   57   98  108   73   35   35  109  102   23   11   28  227
   27  963 1362  102  100  232  177   13  277  255   46   26  322   18
   12  107  794  350  526  467  118   62  254  247  418  219  234  179
   44  410   26  398  139  419 1156  195  163  504   40  358   89  686
  529  683  238 1051  121 1108  281  224  923  598   11  250   17  319
  104  172  155  150   26   26  124    7 1258  957  284  553   71  132
  102  102  147  121   67  150  100    8   34   82  176  230   42    6
  365  134   15  461   98  882  198  445  306  176  264   37    8  163
   25   30   36   19  843  394  358 1319    1    9  506  141   41  337
   87  412  338  201  660  403  320  402  249  174  605  221   89  132
   14 

In [3]:
# Capacidad de los clusters
print(example_data["Z"])

[45, 45, 45, 45, 45, 45, 45]


In [4]:
# Matriz de afinidad
print(example_data["OCM"])

[[ 0.  3.  0. ...  0.  2.  1.]
 [ 3.  0.  0. ...  2.  0.  2.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  2.  0. ...  0.  7. 13.]
 [ 2.  0.  0. ...  7.  0. 12.]
 [ 1.  2.  0. ... 13. 12.  0.]]


In [5]:
# Pesos de los skus
print(example_data["W"])

[10.3   10.3   10.4   10.2    8.04   7.12  18.28  18.293 18.252 10.5
 18.32  18.36  18.293 18.44  10.    10.    18.34  15.905 15.1    2.69
 14.94  15.08  17.56  10.3   18.3    6.1   10.2   18.2   10.3   18.28
 10.32  10.2   10.2   18.252  8.1    9.3    9.2    6.     6.     5.98
  9.2    9.2   15.    15.12  18.293  1.033 18.293  1.02   1.17   1.15
  1.02   1.1    1.3    1.3    9.18   1.45   3.2    9.9    9.24   8.18
  1.02   0.84   1.16   2.16   2.088  2.088  0.72   0.84   4.87   6.56
  1.9    1.16   1.16  18.34  17.56  15.     9.12   9.16   5.93   5.93
  0.51   1.98  18.108  1.98  18.    15.121  1.7    2.     2.3    2.3
  9.16  10.8    4.26   4.26   4.26   4.2    4.26  18.34  18.256  1.1
  1.1    1.27   1.     2.6    9.04   9.38   8.     2.6    2.88   1.7
 24.29   2.9    0.98   2.     1.62   2.48   2.15   9.02   2.2    1.6
  1.6   10.05   8.5    1.2    2.5    5.68   5.68   5.68   4.08   4.08
  4.08  18.18   8.     8.     1.365  1.3    7.93   7.93   1.44   1.46
  1.45  18.    12.62  16.

In [6]:
# Tolerancia en pesos por cada clusters
print(example_data["WT"])

[(9, 30), (9, 30), (5, 12), (4, 11), (1, 6), (0, 5), (0, 5)]


In [7]:
# Capacidad de los clusters considerando divisiones
print(example_data["Z_DIV"])

[[45  0]
 [45  0]
 [45  0]
 [45  0]
 [25 35]
 [25 35]
 [25 35]]


In [8]:
# Rotaciónes de los skus (Solo dos tipos: 0 y 1)
print(example_data["division_types"])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0
 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0
 0 1 1 1 1 1 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 1 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 1
 0 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 1]


In [9]:
from warehouse_allocation.algorithms import solve_chung_problem
    
# Resolvamos el problema considerando restricciones de pesos

result_weighted = solve_chung_problem(
    algorithm_name = "NSGA2",
    D=example_data["D"],
    Z=example_data["Z"],
    OCM=example_data["OCM"],
    W=example_data["W"],
    WT=example_data["WT"],
    mutation_prob = 0.1,
    crossover_prob = 0.9,
    affinity_prob = 0.5,
    pop_size = 20,
    n_offsprings = 10,
    iterations = 20,
    verbose = True
)

n_gen |  n_eval |  n_nds  |     eps      |  indicator  
    1 |      20 |      10 |            - |            -
    2 |      30 |      10 |  0.064575146 |        nadir
    3 |      40 |      11 |  0.213074544 |        ideal
    4 |      50 |      11 |  0.125320647 |        ideal
    5 |      60 |      10 |  0.003698156 |        nadir
    6 |      70 |      10 |  0.003480367 |            f
    7 |      80 |      11 |  0.021616451 |        nadir
    8 |      90 |      12 |  0.009923655 |            f
    9 |     100 |      13 |  0.013965668 |        nadir
   10 |     110 |      12 |  0.247042500 |        ideal
   11 |     120 |      15 |  0.004326172 |        ideal
   12 |     130 |      18 |  0.173957578 |        nadir
   13 |     140 |      14 |  0.063016060 |        nadir
   14 |     150 |      14 |  0.006380354 |            f
   15 |     160 |      13 |  0.161039851 |        ideal
   16 |     170 |      13 |  0.011352723 |            f
   17 |     180 |      14 |  0.007095121 |      

In [10]:
# Resolvamos el problema sin restricciones de pesos
result_original = solve_chung_problem(
    processes = 3, # 3 procesos
    algorithm_name = "NSGA2",
    D=example_data["D"],
    Z=example_data["Z"],
    OCM=example_data["OCM"],
    mutation_prob = 0.1,
    crossover_prob = 0.9,
    affinity_prob = 0.5,
    pop_size = 20,
    n_offsprings = 10,
    iterations = 20,
    verbose = True
)

n_gen |  n_eval |  n_nds  |     eps      |  indicator  
    1 |      20 |      10 |            - |            -
    2 |      30 |      14 |  0.441654779 |        ideal
    3 |      40 |      17 |  0.346752400 |        ideal
    4 |      50 |      17 |  0.013828073 |            f
    5 |      60 |      19 |  0.005615269 |            f
    6 |      70 |      20 |  0.012226937 |            f
    7 |      80 |      20 |  0.200163977 |        ideal
    8 |      90 |      15 |  0.015541265 |        ideal
    9 |     100 |      15 |  0.150294068 |        ideal
   10 |     110 |      15 |  0.098060018 |        ideal
   11 |     120 |      15 |  0.010727870 |            f
   12 |     130 |      17 |  0.014178965 |            f
   13 |     140 |      15 |  0.114172171 |        ideal
   14 |     150 |      12 |  0.020741757 |            f
   15 |     160 |      14 |  0.010771870 |            f
   16 |     170 |      14 |  0.018539965 |            f
   17 |     180 |      14 |  0.014626352 |      

In [11]:
# Resolvamos el problema con restricciones de rotación
result_division = solve_chung_problem(
    processes = 2, # 2 procesos
    algorithm_name = "NSGA2",
    D=example_data["D"],
    Z=example_data["Z_DIV"],
    division_types = example_data["division_types"],
    OCM=example_data["OCM"],
    mutation_prob = 0.1,
    crossover_prob = 0.9,
    affinity_prob = 0.5,
    pop_size = 20,
    n_offsprings = 10,
    iterations = 20,
    verbose = True
)

n_gen |  n_eval |  n_nds  |     eps      |  indicator  
    1 |      20 |      11 |            - |            -
    2 |      30 |       7 |  0.255746459 |        ideal
    3 |      40 |       8 |  0.219086184 |        ideal
    4 |      50 |      11 |  0.020144348 |            f
    5 |      60 |      15 |  0.026571614 |        ideal
    6 |      70 |      17 |  0.006600619 |            f
    7 |      80 |      19 |  0.115273712 |        ideal
    8 |      90 |      17 |  0.114288632 |        ideal
    9 |     100 |      18 |  0.075168853 |        ideal
   10 |     110 |      16 |  0.085481008 |        ideal
   11 |     120 |      18 |  0.006559458 |        ideal
   12 |     130 |      17 |  0.008791401 |        ideal
   13 |     140 |      19 |  0.096899959 |        ideal
   14 |     150 |      20 |  0.035874976 |        ideal
   15 |     160 |      20 |  0.012522803 |            f
   16 |     170 |      20 |  0.003863172 |            f
   17 |     180 |      20 |  0.067596761 |      

In [12]:
# Resolvamos el problema con restricciones de rotación + restricción de peso

# No explicitar processes toma por defecto multiprocessing.cpu_count() - 1

result_division_plus_weight = solve_chung_problem(
    algorithm_name = "NSGA2",
    D=example_data["D"],
    Z=example_data["Z_DIV"],
    W = example_data["W"],
    WT=example_data["WT"],
    division_types = example_data["division_types"],
    OCM=example_data["OCM"],
    mutation_prob = 0.1,
    crossover_prob = 0.9,
    affinity_prob = 0.5,
    pop_size = 20,
    n_offsprings = 10,
    iterations = 20,
    verbose = True
)

n_gen |  n_eval |  n_nds  |     eps      |  indicator  
    1 |      20 |       6 |            - |            -
    2 |      30 |       6 |  0.027036443 |            f
    3 |      40 |      10 |  0.333359115 |        ideal
    4 |      50 |      11 |  0.083193700 |        nadir
    5 |      60 |      15 |  0.388273883 |        ideal
    6 |      70 |      15 |  0.058891455 |        nadir
    7 |      80 |      18 |  0.014707793 |        nadir
    8 |      90 |      18 |  0.002316965 |            f
    9 |     100 |      20 |  0.026731470 |        ideal
   10 |     110 |      20 |  0.133811859 |        ideal
   11 |     120 |      19 |  0.012656912 |        ideal
   12 |     130 |      20 |  0.148781092 |        ideal
   13 |     140 |      20 |  0.006893603 |        nadir
   14 |     150 |      19 |  0.006336620 |        ideal
   15 |     160 |      20 |  0.004172377 |            f
   16 |     170 |      20 |  0.004659020 |        nadir
   17 |     180 |      20 |  0.010776616 |      

Los resultados son instancias de la clase [Result](https://pymoo.org/interface/result.html) de ``pymoo``, y contiene la información de las funciones objetivos, de la población final, del óptimo, etc. Los atributos notables son ``Result.F`` y ``Result.X``, que nos entregan los valores de los objetivos y la población (slottings)

In [13]:
# Accedemos a los valores de las funciones objetivos de la población óptima (Pareto Front)
result_original.F

array([[-131533.,   12523.],
       [-117326.,   10024.],
       [-118689.,   10349.],
       [-118657.,   10140.],
       [-154568.,   18041.],
       [-143647.,   13743.],
       [-133807.,   12736.],
       [-137869.,   13107.],
       [-141896.,   13132.],
       [-126897.,   10543.],
       [-117322.,    9905.],
       [-168842.,   19765.],
       [-162381.,   19399.],
       [-136679.,   13074.],
       [-148510.,   13745.],
       [-128335.,   11842.],
       [-172265.,   21954.],
       [-127856.,   10918.]])

In [14]:
result_weighted.F

array([[-131423.,   12095.],
       [-130113.,   11733.],
       [-138636.,   14617.],
       [-131094.,   12012.],
       [-156386.,   16943.],
       [-134003.,   13230.],
       [-130249.,   11856.],
       [-141721.,   15318.],
       [-136717.,   14378.],
       [-151646.,   16007.],
       [-137945.,   14604.],
       [-155356.,   16915.],
       [-147910.,   15984.],
       [-132670.,   12298.],
       [-155266.,   16771.],
       [-132928.,   12992.],
       [-136129.,   13642.],
       [-153079.,   16525.]])

In [15]:
result_division.F

array([[-124356.,   12268.],
       [-196766.,   25729.],
       [-169563.,   18951.],
       [-187195.,   23220.],
       [-188885.,   24518.],
       [-139235.,   13831.],
       [-173204.,   20894.],
       [-171917.,   19308.],
       [-182716.,   22596.],
       [-179790.,   22021.],
       [-155969.,   15562.],
       [-178085.,   20899.],
       [-129601.,   12942.],
       [-146643.,   14413.],
       [-143988.,   14234.],
       [-152196.,   14678.],
       [-126610.,   12381.],
       [-194059.,   25310.],
       [-162336.,   15861.],
       [-135379.,   13156.]])

<div class="alert alert-info">
<b>Observación :</b> Notar que los valores objetivos del problema sin restricciones de pesos son <em> mejores </em>. Esto es natural, mientras más restricciones tiene un problema de optimización, menor es la performance alcanzada.

</div>

Si no se setea el kwarg `processes` entonces por defecto se consideran `processes = multiprocesing.cpu_count() - 1`. Si el valor de `processes` supera la cantidad de cores disponibles se considera `multiprocessing.cpu_count()`.


Dependiendo de la máquina, no siempre `multiprocessing.cpu_count()` (cantidad máxima de cores) performa mejor en tiempos de ejecución. A veces mejor considerar una cantidad menor.

Para acceder a los slotting, el atributo ``Result.X`` es una matriz donde cada fila es un individuo (slotting), la cantidad filas depende de **cuantos individuos tenga el Pareto Front**. Este conjunto de individuos puede ser a lo más el tamaño de la población dado por el parámetro ``pop_size`` (este caso es cuando todos los individuos son óptimos).



In [16]:
# Los valores como variables de la población, cada fila es un individuo (slotting) en su
# forma vectorial de tamaño n_clusters*n_skus
result_original.X

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]])

Para transformar una fila de la matriz poblacional ``Result.X``, a un slotting en su forma matricial, es decir, una matriz binaria de $C$ filas y $Q$ columnas, donde como siempre $C$ es la cantidad de clusters y $Q$ la cantidad de SKUs se accede al método ``matrix_individual`` definido en todas las clases problemas de ``warehouse_allocation``

In [17]:
# Tomamos el primer individuo de la población y lo transformamos a matriz
# Esta matriz tiene tamaño (n_clusters, n_skus), la entrada (k,i), es un valor
# booleano que es True si el SKU número i está alocado en el cluster k, y False en otro caso.
result_original.problem.matrix_individual(result_original.X[0]).shape

(7, 308)

## Indexación 

El orden de indexación viene dado por las coordenas de los vectores de parámetros. Por ejemplo, si el problema de optimización contiene $N$ SKUS, la información del SKU número $i$ es obtenida de las $i-$ésimas entrada de los vectores de demanda y peso. A su vez, la afinidad entre los SKUS $i$ y $j$, corresponde a la entrada $(i,j)$ de la matriz de afinidad. Es responsabilidad del usuario respetar la indexación. Vectores de parámetros mal indexados conllevan a resultados inesperados.

Cada fila del vector ``result.X``, es un individuo de la población óptima que encontró el algoritmo genético, que en este problema en particular representa un slotting. Por ende, el output del solver es una **familia** de slottings. 


In [18]:
# Ejemplo de como transformar el resultado del output genético en un slotting legíble por humanos

import numpy as np

# Códigos SKUs inventandos que simulan los códigos reales
SKUS = [f"SKU_{i}" for i in range(len(example_data["D"]))]

def make_slotting(skus, result, n_ind):
    """Convierte individuo poblacional es slotting
    
    Dado un individuo de la población óptima del
    resultado del algoritmo genético, transforma
    la información binaria a lista de listas,
    donde la coordenada k, son los códigos SKUs
    que pertenecen al cluster número k
    
    """
    try:
        
        ind = result.X[n_ind]
    
    except IndexError:
        print("Ops, no hay tantos individuos en la población")
        raise
    # Transformamos el individuo a su forma matricial
    ind = result.problem.matrix_individual(ind)
    
    return [[SKUS[idx] for idx in np.flatnonzero(clus)] for clus in ind]

# Slotting humano-legíble del individuo número 10
SLOTTING_FROM_IND_10 = make_slotting(SKUS, result_original, 10)


print("SKUS en el cluster 1 ", SLOTTING_FROM_IND_10[0])


SKUS en el cluster 1  ['SKU_9', 'SKU_10', 'SKU_11', 'SKU_13', 'SKU_17', 'SKU_22', 'SKU_43', 'SKU_50', 'SKU_70', 'SKU_76', 'SKU_84', 'SKU_90', 'SKU_98', 'SKU_100', 'SKU_103', 'SKU_104', 'SKU_106', 'SKU_109', 'SKU_117', 'SKU_118', 'SKU_120', 'SKU_127', 'SKU_128', 'SKU_130', 'SKU_133', 'SKU_136', 'SKU_143', 'SKU_144', 'SKU_147', 'SKU_150', 'SKU_151', 'SKU_154', 'SKU_165', 'SKU_169', 'SKU_186', 'SKU_202', 'SKU_204', 'SKU_223', 'SKU_230', 'SKU_259', 'SKU_267', 'SKU_268', 'SKU_269', 'SKU_299', 'SKU_305']


## Operadores de Mating y constraints

El método ``solve_chung_problem`` como se mostró en los ejemplos anteriores usa internamente operadores *mating* que fueron presentados en la sección de [Operadores](Operadores.html). Dichos operadores son *Problem Specific*, esto es, están construídos para el problema que definen. El uso de los operadores garantiza que en cada iteración se respeten las constraints del problema que definen. Pasando ``constraints = True`` al método ``solve_chung_problem``, se evaluan internamente por ``pymoo`` las constraints



In [19]:
# Evalua las constraints en cada iteración
# Notar que siempre el valor cv (avg) es 0, pues
# los operadores respetan las restricciones del problema

result_constraints = solve_chung_problem(
    algorithm_name = "NSGA2",
    D=example_data["D"],
    Z=example_data["Z"],
    OCM=example_data["OCM"],
    W=example_data["W"],
    WT=example_data["WT"],
    mutation_prob = 0.1,
    crossover_prob = 0.9,
    affinity_prob = 0.5,
    pop_size = 20,
    n_offsprings = 10,
    iterations = 20,
    verbose = True,
    constraints = True,
)

n_gen |  n_eval |   cv (min)   |   cv (avg)   |  n_nds  |     eps      |  indicator  
    1 |      20 |  0.00000E+00 |  0.00000E+00 |      10 |            - |            -
    2 |      30 |  0.00000E+00 |  0.00000E+00 |      11 |  0.434665342 |        ideal
    3 |      40 |  0.00000E+00 |  0.00000E+00 |      11 |  0.061238325 |        nadir
    4 |      50 |  0.00000E+00 |  0.00000E+00 |      12 |  0.047085732 |        nadir
    5 |      60 |  0.00000E+00 |  0.00000E+00 |      13 |  0.135688836 |        ideal
    6 |      70 |  0.00000E+00 |  0.00000E+00 |      14 |  0.057374755 |        ideal
    7 |      80 |  0.00000E+00 |  0.00000E+00 |       7 |  0.057931224 |            f
    8 |      90 |  0.00000E+00 |  0.00000E+00 |       8 |  0.046338598 |        ideal
    9 |     100 |  0.00000E+00 |  0.00000E+00 |       9 |  0.040711586 |            f
   10 |     110 |  0.00000E+00 |  0.00000E+00 |       8 |  0.019904274 |            f
   11 |     120 |  0.00000E+00 |  0.00000E+00 |       

**Cuidado**: Pasar `constraints = True` solo tiene sentido en ámbito de desarrollo/testing, pues debido a que los operadores respetan las constraints del problema, nunca se trabajará con población infeasible y solo hará que el algoritmo haga más cálculos.


**Cuidado**: Las constraints no están paralelizadas (No tiene sentido por lo dicho anteriormente).